function createfigure(X1, YMatrix1, Y1, X2, Y2, S1, C1, X3, Y3, C2, X4, Y4, C3, X5, Y5, C4, X6, Y6, C5, X7, Y7, C6, X8, Y8, C7, X9, Y9, C8)
%CREATEFIGURE(X1, YMatrix1, Y1, X2, Y2, S1, C1, X3, Y3, C2, X4, Y4, C3, X5, Y5, C4, X6, Y6, C5, X7, Y7, C6, X8, Y8, C7, X9, Y9, C8)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  Y1:  vector of y data
%  X2:  scatter x
%  Y2:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  X3:  scatter x
%  Y3:  scatter y
%  C2:  scatter c
%  X4:  scatter x
%  Y4:  scatter y
%  C3:  scatter c
%  X5:  scatter x
%  Y5:  scatter y
%  C4:  scatter c
%  X6:  scatter x
%  Y6:  scatter y
%  C5:  scatter c
%  X7:  scatter x
%  Y7:  scatter y
%  C6:  scatter c
%  X8:  scatter x
%  Y8:  scatter y
%  C7:  scatter c
%  X9:  scatter x
%  Y9:  scatter y
%  C8:  scatter c

%  Auto-generated by MATLAB on 29-May-2018 14:55:36

% Create figure
figure('Renderer','painters','OuterPosition',[1 1 959 461]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'Color',[0 0.588235294117647 1]);
set(plot1(2),'Color',[0 1 0.988235294117647]);
set(plot1(3),'Color',[0 1 0.564705882352941]);
set(plot1(4),'Color',[0 1 0.141176470588235]);
set(plot1(5),'Color',[0.282352941176471 1 0]);
set(plot1(6),'Color',[0.705882352941177 1 0]);
set(plot1(7),'Color',[1 0.870588235294118 0]);
set(plot1(8),'Color',[1 0.447058823529412 0]);

% Create plot
plot(X1,Y1,'Color',[0 0.588235294117647 1]);

% Create plot
plot(X1,Y1,'Color',[0 0.588235294117647 1]);

% Create plot
plot(X1,Y1,'Color',[0 0.588235294117647 1]);

% Create scatter
scatter(X2,Y2,S1,C1,'Marker','.');

% Create scatter
scatter(X3,Y3,S1,C2,'Marker','.');

% Create scatter
scatter(X4,Y4,S1,C3,'Marker','.');

% Create scatter
scatter(X5,Y5,S1,C4,'Marker','.');

% Create scatter
scatter(X6,Y6,S1,C5,'Marker','.');

% Create scatter
scatter(X7,Y7,S1,C6,'Marker','.');

% Create scatter
scatter(X8,Y8,S1,C7,'Marker','.');

% Create scatter
scatter(X9,Y9,S1,C8,'Marker','.');

% Create ylabel
ylabel('\DeltaF/F','FontName','Arial');

% Create xlabel
xlabel('time (s)','FontName','Arial');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 250]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.8 -1.1102230246e-16]);
% Set the remaining axes properties
set(axes1,'FontName','Arial','FontSize',12,'LineWidth',0.7499,'TickDir',...
    'out','YTick',[]);
